# Generated by Django 5.2.8 on 2025-12-19 10:10

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': "Page d'accueil", 'verbose_name_plural': "Pages d'accueil"},
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_content',
            field=wagtail.fields.RichTextField(blank=True, help_text="Biographie et présentation de l'artiste", verbose_name='Contenu à propos'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title',
            field=models.CharField(default='À Propos', max_length=255, verbose_name='Titre section à propos'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='URL complète de la page Facebook', verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='gallery_images',
            field=wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Photo'})}, verbose_name='Photos de la galerie'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='gallery_title',
            field=models.CharField(default='Galerie', max_length=255, verbose_name='Titre section galerie'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(default='Humoriste Stand-Up', max_length=255, verbose_name='Sous-titre'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_tagline',
            field=wagtail.fields.RichTextField(blank=True, default='Rire garanti ou remboursé*<br><small>*Conditions non applicables</small>', help_text="Message d'accroche du hero", verbose_name='Accroche'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='WASSIM EL FATH', max_length=255, verbose_name='Titre principal'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='URL complète du profil Instagram', verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='shows',
            field=wagtail.fields.StreamField([('show_date', 5)], blank=True, block_lookup={0: ('wagtail.blocks.DateBlock', (), {'label': 'Date du spectacle'}), 1: ('wagtail.blocks.TimeBlock', (), {'label': 'Heure'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Nom du lieu', 'max_length': 255}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Ville', 'max_length': 255}), 4: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL vers le site de billetterie (optionnel)', 'label': 'Lien billetterie', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('date', 0), ('time', 1), ('venue', 2), ('city', 3), ('ticket_link', 4)]], {})}, verbose_name='Dates de spectacles'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='shows_title',
            field=models.CharField(default='Prochaines Dates', max_length=255, verbose_name='Titre section spectacles'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tiktok_url',
            field=models.URLField(blank=True, help_text='URL complète du profil TikTok', verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='URL complète de la chaîne YouTube', verbose_name='YouTube'),
        ),
    ]
