# Generated by Django 5.2.8 on 2025-12-19 10:55

import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_options_homepage_about_content_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Texte affiché au-dessus du formulaire', verbose_name="Texte d'introduction")),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True, help_text="Texte affiché après l'envoi du formulaire", verbose_name='Message de remerciement')),
                ('contact_email', models.EmailField(blank=True, help_text='Email où recevoir les messages du formulaire', max_length=254, verbose_name='Email de réception')),
            ],
            options={
                'verbose_name': 'Page Contact',
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='GalleryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name="Texte d'introduction")),
                ('gallery_images', wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Photo'})}, verbose_name='Photos de la galerie')),
            ],
            options={
                'verbose_name': 'Page Galerie',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PressPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name="Texte d'introduction")),
                ('press_articles', wagtail.fields.StreamField([('article', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Ex: 'Le Parisien', 'Télérama', 'France Inter'", 'label': 'Nom de la publication', 'max_length': 255}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('paper', '📰 Article papier (PDF ou image)'), ('online', '🌐 Article en ligne (lien)')], 'label': "Type d'article"}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': "Upload du scan de l'article papier", 'label': "Scan de l'article (image ou PDF)", 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': "URL complète de l'article en ligne", 'label': "Lien vers l'article", 'required': False}), 4: ('wagtail.blocks.DateBlock', (), {'label': 'Date de publication', 'required': False}), 5: ('wagtail.blocks.TextBlock', (), {'help_text': "Citation marquante de l'article", 'label': 'Extrait / Citation', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('publication_name', 0), ('article_type', 1), ('paper_file', 2), ('article_url', 3), ('publication_date', 4), ('excerpt', 5)]], {})}, verbose_name='Articles de presse')),
            ],
            options={
                'verbose_name': 'Page Presse',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ShowsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Texte affiché en haut de la page (optionnel)', verbose_name="Texte d'introduction")),
                ('shows', wagtail.fields.StreamField([('show', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Ex: 'Wassim en rodage', 'One Man Show', etc.", 'label': 'Titre du spectacle', 'max_length': 255}), 1: ('wagtail.blocks.DateBlock', (), {'help_text': 'Format: JJ/MM/AAAA', 'label': 'Date du spectacle'}), 2: ('wagtail.blocks.TimeBlock', (), {'help_text': 'Ex: 20:30', 'label': 'Heure', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "Ex: 'Théâtre du Rond-Point'", 'label': 'Nom du lieu', 'max_length': 255}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Ville', 'max_length': 100}), 5: ('wagtail.blocks.TextBlock', (), {'help_text': 'Courte description du spectacle', 'label': 'Description', 'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': "Image de l'affiche du spectacle", 'label': 'Affiche', 'required': False}), 7: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL vers le site de réservation', 'label': 'Lien billetterie', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title', 0), ('date', 1), ('time', 2), ('venue', 3), ('city', 4), ('description', 5), ('poster', 6), ('ticket_link', 7)]], {})}, verbose_name='Spectacles')),
            ],
            options={
                'verbose_name': 'Page Spectacles',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact (footer)')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='TikTok')),
                ('snapchat_url', models.URLField(blank=True, verbose_name='Snapchat')),
                ('linktree_url', models.URLField(blank=True, help_text='https://linktr.ee/wassimelfath', verbose_name='Linktree')),
                ('google_analytics_id', models.CharField(blank=True, help_text='Format: G-XXXXXXXXXX ou UA-XXXXXXXXX-X', max_length=50, verbose_name='ID Google Analytics')),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': "Page d'accueil"},
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='about_content',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='about_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='gallery_images',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='gallery_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_tagline',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='shows',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='shows_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='tiktok_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_shows_title',
            field=models.CharField(default='Prochains Spectacles', max_length=255, verbose_name='Titre de la section spectacles'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Courte présentation de Wassim (2-3 phrases)', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Photo principale'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(default='Comédien Stand-Up', max_length=255, verbose_name='Sous-titre'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='Wassim El Fath', help_text='Grand titre affiché en haut de page', max_length=255, verbose_name='Titre principal'),
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(help_text='Texte de présentation de Wassim', verbose_name='Biographie')),
                ('portrait_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Photo portrait')),
            ],
            options={
                'verbose_name': 'Page À Propos',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='home.contactpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
