# Generated by Django 5.2.8 on 2025-12-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contactpage_gallerypage_presspage_showspage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='Wassim EL FATH', help_text='Grand titre affiché en haut de page', max_length=255, verbose_name='Titre principal'),
        ),
    ]
