# Generated by Django 5.2.9 on 2025-12-19 16:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_hero_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, verbose_name="Texte d'introduction\n    📸 Page galerie photos\n    \n    Affiche une grille de photos de Wassim El Fath.\n    "),
        ),
    ]
