# Generated by Django 5.2.9 on 2025-12-20 11:38

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_gallerypage_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, verbose_name="Texte d'introduction"),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='Wassim El Fath', help_text='Grand titre affiché en haut de page', max_length=255, verbose_name='Titre principal'),
        ),
    ]
