# Generated by Django 5.2.9 on 2025-12-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_gallerypage_intro_alter_homepage_hero_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Paramètres du site'},
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='Format: G-XXXXXXXXXX', max_length=50, verbose_name='ID Google Analytics'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='linktree_url',
            field=models.URLField(blank=True, help_text='Ex: https://linktr.ee/wassimelfath', verbose_name='Linktree'),
        ),
    ]
