# Generated by Django 5.2.9 on 2025-12-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='test_field',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
