# Generated by Django 5.2.9 on 2025-12-22 14:47

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_contactpage_contact_image_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contactpage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='gallerypage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='presspage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='showspage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={},
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='linktree_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='snapchat_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='test_field',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='body',
            field=wagtail.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='portrait_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='contact_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='thank_you_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='gallery_images',
            field=wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Photo'})}),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_shows_title',
            field=models.CharField(default='Prochains Spectacles', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(default='Comédien Stand-Up', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='Wassim El Fath', max_length=255),
        ),
        migrations.AlterField(
            model_name='presspage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='presspage',
            name='press_articles',
            field=wagtail.fields.StreamField([('article', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Nom de la publication', 'max_length': 255}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('paper', '📰 Article papier (PDF ou image)'), ('online', '🌐 Article en ligne (lien)')], 'label': "Type d'article"}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': "Scan de l'article", 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': "Lien vers l'article", 'required': False}), 4: ('wagtail.blocks.DateBlock', (), {'label': 'Date de publication', 'required': False}), 5: ('wagtail.blocks.TextBlock', (), {'label': 'Extrait / Citation', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('publication_name', 0), ('article_type', 1), ('paper_file', 2), ('article_url', 3), ('publication_date', 4), ('excerpt', 5)]], {})}),
        ),
        migrations.AlterField(
            model_name='showspage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='showspage',
            name='shows',
            field=wagtail.fields.StreamField([('show', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Titre du spectacle', 'max_length': 255}), 1: ('wagtail.blocks.DateBlock', (), {'label': 'Date du spectacle'}), 2: ('wagtail.blocks.TimeBlock', (), {'label': 'Heure', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Nom du lieu', 'max_length': 255}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Ville', 'max_length': 100}), 5: ('wagtail.blocks.TextBlock', (), {'label': 'Description', 'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Affiche', 'required': False}), 7: ('wagtail.blocks.URLBlock', (), {'label': 'Lien billetterie', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title', 0), ('date', 1), ('time', 2), ('venue', 3), ('city', 4), ('description', 5), ('poster', 6), ('ticket_link', 7)]], {})}),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
