# Generated by Django 5.2.9 on 2025-12-22 18:04

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_contactpage_linktree_url_homepage_spectacle_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='linktree_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='gallery_images',
            field=wagtail.fields.StreamField([('photo_cliche', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Photo'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ex: Moi après 3 cafés...', 'label': 'Légende marrante', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1)]], {'label': 'Cliché avec légende'})}),
        ),
    ]
