# Generated by Django 5.2.9 on 2025-12-23 09:51

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_sitesettings_linktree_url_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(verbose_name='Avis / Remarque')),
                ('author', models.CharField(max_length=255, verbose_name='Nom du spectateur')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
            },
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='linktree_url',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='tiktok_url',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='funny_pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='gallery_images',
            field=wagtail.fields.StreamField([('photo_cliche', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Photo'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Légende marrante', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1)]], {'label': 'Cliché avec légende'})}),
        ),
        migrations.AlterField(
            model_name='presspage',
            name='press_articles',
            field=wagtail.fields.StreamField([('article', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Nom de la publication', 'max_length': 255}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': "Logo ou Photo de l'article", 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('paper', '📰 Article papier (PDF ou image)'), ('online', '🌐 Article en ligne (lien)')], 'label': "Type d'article"}), 3: ('wagtail.blocks.URLBlock', (), {'label': "Lien vers l'article", 'required': False}), 4: ('wagtail.blocks.DateBlock', (), {'label': 'Date de publication', 'required': False}), 5: ('wagtail.blocks.TextBlock', (), {'label': 'Extrait / Citation', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('publication_name', 0), ('publication_logo', 1), ('article_type', 2), ('article_url', 3), ('publication_date', 4), ('excerpt', 5)]], {})}),
        ),
    ]
