# Generated by Django 5.2.9 on 2025-12-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_testimonial_delete_sitesettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram (URL)')),
                ('tiktok_url', models.URLField(blank=True, null=True, verbose_name='TikTok (URL)')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='YouTube (URL)')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook (URL)')),
                ('linktree_url', models.URLField(blank=True, default='https://linktr.ee/wassimelfath', null=True, verbose_name='Linktree (URL)')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
